# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05abaa4ac2374907ff0c3d1d8fe2ee5112d0fd59d93f8dfda078e987113682353a12a86f351652f77c326546eff66c2eaebe0f2100b2b15e492600e5515177ce

test:
  secret_key_base: ce100e80e0d0d71622fc2f002bd61682c014b50bb1c107c0175b48ea17f064da7ab7ee7ae0df7a25a00308d83907b64f1b68e6852de88533a1a7691584e68b0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
